import {Dimensions, StyleSheet} from 'react-native';
const {width, height} = Dimensions.get('window');
export default StyleSheet.create({
  container: {flex: 1, backgroundColor: 'white'},
  subContainerCartItems: {
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginBottom: 10,
  },
  subContainerCartItemsTwo: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 75,
    height: 75,
    backgroundColor: 'pink',
    borderRadius: 10,
  },
  btnColor: {
    paddingHorizontal: '5%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 30,
    height: 50,
    backgroundColor: 'pink',
  },
  btnColorPink: {
    paddingHorizontal: '5%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 30,
    height: 50,
    backgroundColor: '#F0F8FF',
  },
  btnContainer: {
    width: '80%',
    height: 50,
    marginTop: '6%',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    alignSelf: 'center',
    flexDirection: 'row',
    backgroundColor: '#F0F8FF',
    borderRadius: 30,
  },
  cartItemsContainer: {
    padding: 12,
    borderWidth: 0.3,
    borderColor: 'grey',
    borderRadius: 20,
    marginTop: 10,
    marginBottom: '5%',
    width: '90%',
    alignSelf: 'center',
  },
  OrderProgressItems: {
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 4,
    borderColor: '#FFCB00',
    width: 42,
    height: 42,
    borderRadius: 42 / 2,
  },
  OrderProgress: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 12,
    borderWidth: 0.3,
    borderColor: 'grey',
    borderRadius: 20,
    marginTop: 10,
    marginBottom: 5,
    width: '90%',
    alignSelf: 'center',
  },
  progressBar: {
    backgroundColor: 'red',
    height: 4,
    alignSelf: 'center',
    width: 22,
  },
  subTitxt: {
    color: 'black',
    fontWeight: '700',
    fontSize: 18,
  },
  subTitxtTwo: {
    color: 'black',
    fontWeight: '600',
    fontSize: 17,
  },
  contiBtn: {
    marginTop: '5%',
    marginBottom: '5%',
    alignSelf: 'center',
    width: '80%',
    height: 43,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'magenta',
    borderRadius: 30,
  },
  orderDetailTxt: {
    fontSize: 25,
    color: 'black',
    fontWeight: '600',
    marginTop: '2%',
    alignSelf: 'center',
  },
  subContainer: {
    marginBottom: 5,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  statusContainer: {
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  itemLenthContainer: {
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  orderContainer: {
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginBottom: '6%',
    marginTop: '3%',
  },
  subOrderContainer: {
    width: width - 20,
    height: 'auto',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'column',
  },
  orderImgs: {
    width: width - 30,
    height: 140,
    borderRadius: 10,
  },
  priceTxtContainer: {
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  txtStepTitle: {color: 'grey', fontFamily: 'RobotoSlab-Bold', fontSize: 10},
  txtSteps: {
    color: 'black',
    fontFamily: 'RobotoSlab-Bold',
    fontSize: 14,
  },
});
