import {Dimensions, StyleSheet} from 'react-native';
const {width, height} = Dimensions.get('window');
export default StyleSheet.create({
  labelInputText: {
    textAlign: 'left',
    marginVertical: 10,
    fontSize: 13,
  },
  Modal: {
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    marginTop: '15%',
    backgroundColor: 'white',
  },
  modalInnerBtn: {
    width: '13%',
    borderRadius: 25,
    height: '6%',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '3%',
    backgroundColor: 'orange',
  },
  containerContent: {
    width: width,
    height: height / 1.6,
    backgroundColor: 'white',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    alignItems: 'center',
    flexDirection: 'column',
    position: 'absolute',
    bottom: 0,
    justifyContent: 'center',
  },

  exploreSection: {
    paddingHorizontal: 16,
    paddingTop: 30,
  },
  exploreHeader: {
    fontWeight: '700',
    marginBottom: 30,
    textAlign: 'center',
    fontSize: 19,
  },
  exploreContent: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  singleExplore: {
    height: 80,
    width: '28%',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.5,
    shadowRadius: 1,
    elevation: 1,
    backgroundColor: 'white',
    margin: 1,
    marginBottom: 20,
    borderRadius: 20,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    alignSelf: 'flex-start',
    paddingVertical: 10,
  },
  exploreText: {
    fontSize: 12,
    color: 'white',
    fontWeight: '700',
  },
  buttons: {
    width: 400,
    height: 150,
  },
  passwordContainer: {
    flexDirection: 'row',
    backgroundColor: '#F6F3F5',
    borderRadius: 25,
    padding: 12,
    width: '100%',
    height: 45,
    marginBottom: 20,
    alignItems: 'center',
  },
  inputStyle: {
    flex: 1,
  },
  imgStyle: {
    width: 34,
    height: 34,
  },
});
